### ISSUE TITLE
Check Permissions in /data/data

### ISSUE THREAD

**Issue by Tiefkuehlpizze** [Tiefkuehlpizze/oandbackupx#1]
```
drwxr-x--x  4 u0_a94    u0_a94    4096 2019-11-15 13:05 com.google.android.launcher
drwxrwx--x 12 u0_a121   u0_a121   4096 2020-06-28 12:25 com.spotify.music
drwx------  8 u0_a123   u0_a123   4096 2020-06-28 12:25 com.sunborn.girlsfrontline.en
```
`com.spotify.music` has been restored while `com.sunborn.girlsfrontline.en` was installed by Google Play.
But also some other system apps have these permissions set.

It does not seem to break anything, but data privacy might be reduced.

**Comment by machiav3lli** [comment]
This was one thing I was thinking off, changing permissions back after restore. As using "the" toybox now, should saves us from problems that was to be solved in oab-utils.

**Comment by machiav3lli** [comment]
This considering how much complicated the permission groups of the files is not possible in shell, we should be depending on tar for it

**Comment by Tiefkuehlpizze** [comment]
After some more rounds of self-reviewing, I finally got backup and restore working… at least if you just moving the data back in place. The permissions are now an issue. I'll push a bunch of commits in the next minutes.

```06-30 22:41:42.530 20876 20938 W FileUtils: Failed to chmod(/data/user/0/com.spotify.music/files): android.system.ErrnoException: chmod failed: EPERM (Operation not permitted)                                                              
06-30 22:41:42.533 20876 20969 W FileUtils: Failed to chmod(/data/user/0/com.spotify.music/files): android.system.ErrnoException: chmod failed: EPERM (Operation not permitted)
06-30 22:41:42.558 20876 20897 E SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/com.spotify.music/shared_prefs/io.fabric.sdk.android:fabric:io.fabric.sdk.android.n.xml                                             
06-30 22:41:42.565 20876 20932 E CrashlyticsCore: Failed to execute task.                                              
06-30 22:41:42.565 20876 20932 E CrashlyticsCore: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File[] java.io.File.listFiles(java.io.FilenameFilter)' on a null object reference
```
```
serranoltexx:/data/user/0/com.spotify.music # ls -lah
total 30K
drwx------  12 u0_a124 u0_a124       4.0K 2020-06-30 22:41 .
drwxrwx--x 149 system  system        8.0K 2020-06-30 22:33 ..
drwxr-x---   2 root    root          4.0K 2020-06-30 22:40 app_download_internal
drwxr-x---   2 root    root          4.0K 2020-06-30 22:40 app_remote-config
drwxr-x---   2 root    root          4.0K 2020-06-30 22:40 app_service-tombstones
drwxr-x---   2 root    root          4.0K 2020-06-30 22:40 app_textures
drwxr-x---   3 root    root          4.0K 2020-06-30 22:40 app_webview
drwxrws--x   4 u0_a124 u0_a124_cache 4.0K 2020-06-30 22:41 cache
drwxr-x---   2 root    root          4.0K 2020-06-30 22:40 databases
drwxr-x---   9 root    root          4.0K 2020-06-30 22:40 files
lrwxrwxrwx   1 root    root            60 2020-06-30 22:35 lib -> /data/app/com.spotify.music-OEk414F0CbYLChcVoG7Llg==/lib/arm
drwxr-x---   2 root    root          4.0K 2020-06-30 22:40 no_backup
drwxr-x---   2 root    root          4.0K 2020-06-30 22:40 shared_prefs
``` 
I'll see, what I can do about it.

**Comment by machiav3lli** [comment]
I'll be pushing today at night or tommorrow morning the latest changes from my side. Unfortunately am stuck for now in the exams month and so merging those changes to the main repo doesn't come in question for now.

Should everything work as planed, I'll be releasing 2.0.0 on the weekend and with that make FDroid releases update automaticlly and there's a small possibility to have Weblate ready by then. Write me on TG, if you thing we should establish a dev-ch on Riot(as long as it's called so) or zulip, a dev-document in the repo or just leave it the way it is.

**Comment by Tiefkuehlpizze** [comment]
I would wait with the 2.0.0 release. My recent changes (tar.gz, aes encryption, backup directory structure change) will render all existent backups useless, if we don't implement something to support those structures.

I'm trying to keep my branch up to date and it I could rebase onto the latest changes without any problems.

I don't mind freezing the public development for a while. I could still publish "unofficial" versions to interested people. Due to the issues I found, I would not recommend to rely on OAndBackupX as main backup solution. Once the core feature backup & restore is working, the user interface/experience can be improved.

Once the permissions are set correctly, the only thing left is the issue with symlinks and other special files. I'm worrying most about symlinks because they make the app a timebomb and use more space than a clean installed version.

However. I'll see what I'll do about it. When I'm done here, I'll also take a break. Good luck with your exams.

P.S.: As long as it's just us two, I'm fine with the TG for quick chats and issues on the main project. I might create some with issues and ideas for improvement. Then everyone can discuss them there. As I said: My fork's issues are just for dumping what I'm thinking and to make my development transparent

**Comment by Tiefkuehlpizze** [comment]
Problem solved in my development branch. The directories are create by the package manager and the contents are copy/moved into it and then chown'd.
