### ISSUE TITLE
Symlinks and tar.gz issues

### ISSUE THREAD

**Issue by Tiefkuehlpizze** [Tiefkuehlpizze/oandbackupx#3]
Just a quick update, before I'm leaving for a short night:
I'm reworking the whole core backup stuff (namely ShellCommands.java).
At some points, I ran into issues just related to SDK <26 (namely Android 7.x). I'm currently testing on Android 7 and I've noticed that many apps  are not available on the Play Store (many Games and Spotify). I guess it's because of split APK. So Titanium Backup would probably perform well on Android 7.x.

As you might have seen, I have `.tar.gz` archiving implemented. It's working fine and I think, I even got the crypto running (some password to key expansion with PBKDF2 and then wrap the tar.gz output stream through it).

But now the bummer: I already mentioned the problem with symlinks and zipfiles the other day and when I was testing the restore function, I've noticed issues with the `lib` directory in the app's data because it's a symlink. Too many symlinks. Well. The backup procedure does not create symlinks in the tar.gz archive. Even when I tried to implement it. That's because it's copying the data to the external storage first which is formatted in FAT. And FAT does not support symlinks.

I guess, the restore of the data works in the released versions, because it's dereferencing the symlinks and replaces it with the actual files. This might go well for some time, but I guess the time will come, when the app updates the original file and you'll have mixed versions in your data. Either you'll have to fix it manually or you'll have to delete the app's data.

I can think of another solution which is to use toybox's tar command to create the archive right from the data directory and to the encryption afterwards. It would double the writes on the storage if you have encryption enabled because it would first create the archive and then encrypt it (and being picky: it leaves the traces of the unencrypted deleted archive, so an attacker could be able to restore the data).

Last for today, I want to mention a potential bug with the `AppInfo` class, because it stores and restores the original data directories, which is fine on the same device. On my emulator, I have adopted storage and then it tries to restore the data to `/mnt/expand/86e4a97c-661b-4611-971a-b66b093be72e/user/0/com.supercell.clashofclans`. Obviously a dynamic path that is different after a wipe or change of device. So I needed to get the fresh path from the package manager.
I guess you also have noticed, that the app does not do a good job updating the information an action and here it even causes issues on the technical site.

That's so far from my site. I'll go on tomorrow. I need some sleep now.

**Comment by machiav3lli** [comment]
Updating information on actions in appsheet shouldn't be that of a problem to hack. Already thought of a solution for it.

The only other way I could think of is fetching info directly in oncreate, which makes sense if the (proto-)system to be thought of is so dynamic, which I don't think it is. But handling the appinfo list could be optimized/changed to better reflect changes. I have some ideas on the topic, but not much time. 

Maybe an open dev-git would make sense for better communication?? Dev-talk in the main repo could make it somehow cluttered and documentation isn't a thing I wish for or that we can keep it maintained.

**Comment by Tiefkuehlpizze** [comment]
Solved. :)
